spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoppinglist_db
    username: shoppinglist
    password: shoppinglist
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true # for development true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
